### PR TITLE
Fix unicode usage to make python3 work again

### PR DESCRIPTION
**Pull request by hackedbellini**

### CODE REVIEW

**Comment by hackedbellini** [comment]
@wkoot the fail doesn't seem to be related to my change. Also, without this change, python3 isn't working at all.

**Comment by wkoot** [comment]
It is related to your change; default behaviour for `str(class)` calls `class.__repr__`, but `six.u(class)` would call `class.replace` which is not there. See the following:
```
>>> class Blub(object):
...  a = 123
...  def __repr__(self):
...    return str(self.a)
...
>>>
>>> str(Blub())
'123'
>>>
>>> import six
>>> six.u(Blub())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/six.py", line 647, in u
    return unicode(s.replace(r'\\', r'\\\\'), "unicode_escape")
AttributeError: 'Blub' object has no attribute 'replace'
```

**Comment by wkoot** [comment]
This was cherry-picked from https://github.com/facebookarchive/python-instagram/pull/195/commits/2d5768b6f71f4312da0bf4084a6ca1fb7eba7525 by the way. Interesting that it's failing for you, a test case would be really welcome

**Comment by wkoot** [comment]
Implemented in https://github.com/wkoot/python-instagram/pull/16

**Pull request closed without merging**
